'use strict';
const data=window.CATALOG;const items=data.items;const $=s=>document.querySelector(s);let active=null;let slide=0;let variant='SFW';let displayed=[];
for(const item of items)Object.assign(item,window.CAMPAIGN.characters[item.id]||{});
const labels={characters:'Персонажи',chibi:'Chibi',diorama:'Диорама'};
function size(bytes){if(bytes===null||bytes===undefined)return '';return bytes>=1024**3?(bytes/1024**3).toFixed(2).replace('.',',')+' ГБ':bytes<1024**2?Math.max(1,Math.round(bytes/1024))+' КБ':Math.round(bytes/1024**2)+' МБ'}
function ready(a,p){const available=Boolean(p&&p.path);if(available){a.href=p.path;a.setAttribute('download','');a.removeAttribute('aria-disabled');a.removeAttribute('tabindex');a.title='';if(p.path.startsWith('https://')){a.removeAttribute('download');a.removeAttribute('target');a.rel='noopener noreferrer'}}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');a.tabIndex=-1;a.title='Файл пока не опубликован'}return available}
function makeButton(label,p,style){const a=document.createElement('a');a.className='button '+style;const caption=document.createElement('span');caption.textContent=label;const meta=document.createElement('small');meta.textContent=p?size(p.bytes):'';a.append(caption,meta);if(!ready(a,p)){caption.textContent=label.includes('STL')?'STL пока недоступны':label.includes('Chitubox')?'Chitubox пока недоступен':label.includes('бюста')?'Рендеры бюста пока недоступны':'Рендеры пока недоступны';meta.textContent='';}return a}
function card(item){const el=document.createElement('article');el.className='card'+(!item.stlCount||(item.bustView&&!item.bust)?' missing-card':'');const cover=document.createElement('button');cover.className='cover';cover.setAttribute('aria-label','Открыть '+(item.displayName||item.name));const img=document.createElement('img');img.src=item.cover;img.alt=(item.displayName||item.name);img.loading='lazy';img.width=600;img.height=700;const hint=document.createElement('span');hint.className='cover-label';hint.textContent='Галерея и файлы';cover.append(img,hint);cover.addEventListener('click',()=>openGallery(item));const body=document.createElement('div');body.className='card-body';const cat=document.createElement('p');cat.className='card-category';cat.textContent=item.role||labels[item.category];const name=document.createElement('h3');const titleButton=document.createElement('button');titleButton.className='character-title';titleButton.textContent=(item.displayName||item.name);titleButton.setAttribute('aria-label','Открыть файлы '+(item.displayName||item.name));titleButton.addEventListener('click',()=>openGallery(item));name.append(titleButton);const tags=document.createElement('div');tags.className='tags';const tagLabels=[item.stlCount+' STL',...(item.supported?['С поддержками']:[]),...(item.bust?['Бюст']:[]),...(item.gallery.some(x=>x.label==='NSFW')?['SFW / NSFW']:[])];for(const t of tagLabels){const span=document.createElement('span');span.textContent=t;tags.append(span)}const buttons=document.createElement('div');buttons.className='card-downloads';buttons.append(makeButton('Скачать STL',item.model,'primary'),makeButton('Скачать рендеры',item.renders,'secondary'));body.append(cat,name,tags);if(!item.stlCount||(item.bustView&&!item.bust)){const warning=document.createElement('p');warning.className='missing';warning.textContent=item.bustView?'НЕТ STL БЮСТА':'НЕТ STL';body.append(warning)}body.append(buttons);if(item.previewNote&&item.previewNote!=='Рендер общей диорамы'){const note=document.createElement('p');note.className='preview-note';note.textContent=item.previewNote;body.append(note)}el.append(cover,body);el.addEventListener('click',event=>{if(!event.target.closest('a,button'))openGallery(item)});return el}
function missingCard(name,role,locked=false){const el=document.createElement('article');el.className='card unavailable'+(locked?'':' missing-card');const title=document.createElement('h3');title.textContent=name;const subtitle=document.createElement('p');subtitle.className='eyebrow';subtitle.textContent=role;const note=document.createElement('p');note.className=locked?'locked-note':'missing';note.textContent=locked?'Цель не открыта на Kickstarter':'Файлы пока недоступны';el.append(subtitle,title,note);return el}
const sectionIds=['core','busts','chibi','diorama','stretch'];
const bustCovers={'briar-vess':'briar','wolfsbane':'marrok','bloodhood':'rosalind'};
function sectionHeader(title,description){
  const header=document.createElement('header');header.className='section-header';
  const heading=document.createElement('h2');heading.textContent=title;header.append(heading);
  if(description){const p=document.createElement('p');p.className='section-description';p.textContent=description;header.append(p)}
  return header;
}
function render(){
  const root=$('#cards');root.replaceChildren();
  window.CAMPAIGN.sections.forEach((section,i)=>{
    const id=sectionIds[i];const block=document.createElement('section');block.id=id;
    block.className='campaign-section '+id+'-section'+(section.bust?' bust-section':'');
    block.append(sectionHeader(section.title,section.description));
    const grid=document.createElement('div');grid.className='grid';
    for(const id of section.ids){
      const item=items.find(x=>x.id===id);if(!item)continue;
      if(section.bust&&!item.bust&&!item.bustCover){grid.append(missingCard((item.displayName||item.name)+' — бюст',item.role));continue}
      const view=section.bust?{...item,bustView:true}:item;const el=card(view);
      if(section.bust){
        const name=item.displayName||item.name;
        el.querySelector('.character-title').textContent=name;
        el.querySelector('.cover').setAttribute('aria-label','Открыть бюст '+name);
        el.querySelector('.character-title').setAttribute('aria-label','Открыть файлы бюста '+name);
        el.querySelector('.card-downloads').remove();el.querySelector('.tags').remove();
        el.querySelector('.cover-label').textContent='Бюст и файлы';
        if(item.bustCover)el.querySelector('.cover img').src=item.bustCover;else if(bustCovers[id])el.querySelector('.cover img').src='assets/brand/bust-'+bustCovers[id]+'.jpg';
      }
      grid.append(el);
    }
    for(const entry of section.missing||[])grid.append(missingCard(entry.name,entry.role));
    block.append(grid);root.append(block);
  });
  const locked=document.createElement('section');locked.className='campaign-section locked-section';
  locked.append(sectionHeader('Неоткрытая история',''),missingCard('Aveline Glass','The Fairest',true));root.append(locked);
}
function renderFiles(item){const target=$('#character-file-list');target.replaceChildren();const files=(item.files||[]).filter(f=>!item.bustView||((f.type==='stl'||f.type==='chitubox')?/bust/i.test(f.relative):f.type==='render'?f.relative.startsWith('Рендеры/Бюст/'):true));$('#file-count').textContent=files.length;const types=[['chitubox','Chitubox'],['stl','STL'],['render','Рендеры и видео']];for(const [type,label] of types){const matches=files.filter(x=>x.type===type);if(!matches.length)continue;const group=document.createElement('details');group.className='file-group';group.open=type==='chitubox'||(item.bustView&&type==='stl');const summary=document.createElement('summary');const caption=document.createElement('span');caption.textContent=label;const count=document.createElement('span');count.textContent=matches.length;summary.append(caption,count);group.append(summary);let previous='';for(const f of matches){if(f.group!==previous&&type!=='chitubox'){const heading=document.createElement('p');heading.className='file-subgroup';heading.textContent=f.group.split('/').slice(1).join(' · ')||label;group.append(heading);previous=f.group}const row=document.createElement('a');row.className='file-row';const name=document.createElement('span');name.className='file-name';name.textContent=f.name;const meta=document.createElement('span');meta.className='file-meta';meta.textContent=size(f.bytes);row.append(name,meta);ready(row,f);if(f.path)row.setAttribute('aria-label','Скачать '+f.name);else{row.removeAttribute('aria-disabled');row.removeAttribute('tabindex');row.title=data.mode==='online'?'Этот файл находится внутри ZIP-комплекта':'';}group.append(row)}target.append(group)}}
function showSlide(){displayed=active.gallery.filter(x=>(active.bustView?x.scope==='bust':x.scope!=='bust')&&(variant==='NSFW'?x.label==='NSFW':x.label!=='NSFW'));slide=Math.max(0,Math.min(slide,displayed.length-1));const current=displayed[slide];if(current){$('#gallery-image').src=current.src;$('#gallery-image').alt=(active.displayName||active.name)+' — '+current.label+' '+(slide+1)}else{$('#gallery-image').removeAttribute('src');$('#gallery-image').alt='Рендеров нет'}$('#gallery-counter').textContent=(displayed.length?slide+1:0)+' / '+displayed.length;$('#prev').disabled=slide===0;$('#next').disabled=slide>=displayed.length-1;$('#gallery-note').classList.toggle('missing',active.bustView&&!active.bust);$('#gallery-note').textContent=active.bustView?(!active.bust?'НЕТ STL БЮСТА. Пока доступны только рендеры.':'Файлы бюста показаны отдельно. Полный комплект STL также содержит детали персонажа.'):active.previewNote;for(const b of document.querySelectorAll('[data-variant]'))b.setAttribute('aria-pressed',String(b.dataset.variant===variant));const thumbs=displayed.map((x,i)=>{const b=document.createElement('button');b.className='thumbnail'+(i===slide?' current':'');b.setAttribute('aria-label','Рендер '+(i+1));b.setAttribute('aria-pressed',String(i===slide));const image=document.createElement('img');image.src=x.src;image.alt='';image.loading='lazy';b.append(image);b.addEventListener('click',()=>{slide=i;showSlide()});return b});$('#gallery-thumbnails').replaceChildren(...thumbs)}
function openGallery(item){active=item;slide=0;variant='SFW';$('#gallery-title').textContent=(item.displayName||item.name)+(item.bustView?' — бюст':'');$('#character-role').textContent=[item.chapter?'Глава '+item.chapter:'',item.role].filter(Boolean).join(' · ');$('#character-lore').textContent=item.lore||'Миниатюра из коллекции Wonderland Leaks Through.';$('#gallery-variants').hidden=item.bustView||!item.gallery.some(x=>x.label==='NSFW');$('#character-downloads').replaceChildren(makeButton('STL — весь комплект',item.bustView&&!item.bust?null:item.model,'primary'),makeButton(item.bustView?'Рендеры бюста — весь комплект':'Рендеры — весь комплект',item.bustView?item.bustRenders:item.renders,'secondary'),...(item.chitubox&&!item.bustView?[makeButton('Скачать Chitubox',item.chitubox,'secondary')]:[]));$('#shared-project-note').hidden=data.mode!=='online'&&!item.files?.some(f=>f.shared);$('#shared-project-note').textContent=data.mode==='online'?'Отдельные файлы находятся внутри ZIP. Скачайте нужный комплект выше.':'Chibi используют общий проект Chitubox.';renderFiles(item);showSlide();$('#gallery').showModal();$('#gallery').scrollTop=0}
$('#close-gallery').addEventListener('click',()=>$('#gallery').close());$('#prev').addEventListener('click',()=>{slide--;showSlide()});$('#next').addEventListener('click',()=>{slide++;showSlide()});for(const b of document.querySelectorAll('[data-variant]'))b.addEventListener('click',()=>{variant=b.dataset.variant;slide=0;showSlide()});$('#gallery').addEventListener('click',e=>{if(e.target===$('#gallery')){const rect=e.target.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)e.target.close()}});$('#gallery').addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&slide<displayed.length-1){slide++;showSlide()}if(e.key==='ArrowLeft'&&slide>0){slide--;showSlide()}});const allReady=ready($('#download-all'),data.all);if(!allReady)$('#download-all span').textContent='Архив готовится';else if(data.all.caption)$('#download-all span').textContent=data.all.caption;$('#all-size').textContent=data.all?'ZIP · '+size(data.all.bytes):'ZIP';$('#publish-note').hidden=data.mode==='local'||(Boolean(data.all&&data.all.path)&&!data.downloadNote);if(data.downloadNote)$('#publish-note').textContent=data.downloadNote;render();
