window.startLibrary = function () {
'use strict';
const data=window.CATALOG;const items=data.items;const $=s=>document.querySelector(s);let active=null;let slide=0;let variant='SFW';let displayed=[];
for(const item of items)Object.assign(item,window.CAMPAIGN.characters[item.id]||{});
const labels={characters:'Characters',chibi:'Chibi',diorama:'Diorama'};
function size(bytes){if(bytes===null||bytes===undefined)return '';return bytes>=1024**3?(bytes/1024**3).toFixed(2)+' GB':bytes<1024**2?Math.max(1,Math.round(bytes/1024))+' KB':Math.round(bytes/1024**2)+' MB'}
function ready(a,p){const available=Boolean(p&&p.path);a.classList.toggle('download-unavailable',!available);a.classList.toggle('download-partial',Boolean(available&&p.partial));a.dataset.archive=p?.archiveName||'';a.dataset.downloadStatus=available?(p.partial?'partial':'ready'):'unavailable';if(available){a.href=p.path;a.setAttribute('download','');a.removeAttribute('aria-disabled');a.removeAttribute('tabindex');a.title=p.unavailableReason||'';if(p.path.startsWith('https://')){a.removeAttribute('download');a.removeAttribute('target');a.rel='noopener noreferrer'}}else{a.removeAttribute('href');a.setAttribute('aria-disabled','true');a.tabIndex=-1;a.title=p?.unavailableReason||'Archive unavailable'}return available}
function makeButton(label,p,style){const a=document.createElement('a');a.className='button '+style;const caption=document.createElement('span');caption.textContent=p?.fallback?label.replace(' — full set','')+(data.tier&&data.tier!=='complete'?' · Set ZIP':' · Collection ZIP'):label;const meta=document.createElement('small');meta.textContent=p?size(p.bytes):'';a.append(caption,meta);if(!ready(a,p)){caption.textContent=p?.unavailableLabel||(label.includes('STL')?'STL unavailable':label.includes('Chitubox')?'Chitubox unavailable':label.toLowerCase().includes('bust')?'Bust renders unavailable':'Renders unavailable');meta.textContent='';}return a}
function card(item){const el=document.createElement('article');el.dataset.character=item.id;el.dataset.view=item.bustView?'bust':'figure';el.className='card'+(!item.stlCount||(item.bustView&&!item.bust)?' missing-card':'');const cover=document.createElement('button');cover.className='cover';cover.setAttribute('aria-label','Open '+(item.displayName||item.name));const img=document.createElement('img');img.src=item.cover;img.alt=(item.displayName||item.name);img.loading='lazy';img.width=600;img.height=700;const hint=document.createElement('span');hint.className='cover-label';hint.textContent='Gallery and files';cover.append(img,hint);cover.addEventListener('click',()=>openGallery(item));const body=document.createElement('div');body.className='card-body';const cat=document.createElement('p');cat.className='card-category';cat.textContent=item.role||labels[item.category];const name=document.createElement('h3');const titleButton=document.createElement('button');titleButton.className='character-title';titleButton.textContent=(item.displayName||item.name);titleButton.setAttribute('aria-label','Open files for '+(item.displayName||item.name));titleButton.addEventListener('click',()=>openGallery(item));name.append(titleButton);const tags=document.createElement('div');tags.className='tags';const tagLabels=[item.stlCount+' STL',...(item.supported?['Pre-supported']:[]),...(item.bust?['Bust']:[]),...(item.gallery.some(x=>x.label==='NSFW')?['SFW / NSFW']:[])];for(const t of tagLabels){const span=document.createElement('span');span.textContent=t;tags.append(span)}const buttons=document.createElement('div');buttons.className='card-downloads';buttons.append(makeButton('Download STL',item.model,'primary'),makeButton('Download renders',item.renders,'secondary'));body.append(cat,name,tags);if(!item.stlCount||(item.bustView&&!item.bust)){const warning=document.createElement('p');warning.className='missing';warning.textContent=item.bustView?'NO BUST STL':'NO STL';body.append(warning)}body.append(buttons);if(item.previewNote&&item.previewNote!=='Shared diorama render'){const note=document.createElement('p');note.className='preview-note';note.textContent=item.previewNote;body.append(note)}el.append(cover,body);el.addEventListener('click',event=>{if(!event.target.closest('a,button'))openGallery(item)});return el}
function missingCard(name,role,locked=false){const el=document.createElement('article');el.className='card unavailable'+(locked?'':' missing-card');const title=document.createElement('h3');title.textContent=name;const subtitle=document.createElement('p');subtitle.className='eyebrow';subtitle.textContent=role;const note=document.createElement('p');note.className=locked?'locked-note':'missing';note.textContent=locked?'Stretch goal not unlocked on Kickstarter':'Files unavailable';el.append(subtitle,title,note);return el}
const sectionIds=['core','busts','chibi','diorama','stretch'];
const bustCovers={'briar-vess':'briar','wolfsbane':'marrok','bloodhood':'rosalind'};
function sectionHeader(title,description){
  const header=document.createElement('header');header.className='section-header';
  const heading=document.createElement('h2');heading.textContent=title;header.append(heading);
  if(description){const p=document.createElement('p');p.className='section-description';p.textContent=description;header.append(p)}
  return header;
}
function render(){
  const root=$('#cards');root.replaceChildren();
  window.CAMPAIGN.sections.forEach((section,i)=>{
    const id=sectionIds[i];if(id==='chibi'&&data.access?.chibi===false)return;const block=document.createElement('section');block.id=id;
    block.className='campaign-section '+id+'-section'+(section.bust?' bust-section':'');
    block.append(sectionHeader(section.title,id==='core'&&data.tier==='core'?'Four chapters of Grimmswood. SFW versions.':section.description));
    if(data.access&&((section.bust&&!data.access.busts)||(id==='diorama'&&!data.access.diorama))){
      block.classList.add('tier-locked');const note=document.createElement('p');note.className='tier-locked-note';note.textContent='Available in Complete Collection';block.append(note);root.append(block);return;
    }
    const grid=document.createElement('div');grid.className='grid';
    for(const id of section.ids){
      const item=items.find(x=>x.id===id);if(!item)continue;
      if(section.bust&&!item.bust&&!item.bustCover){grid.append(missingCard((item.displayName||item.name)+' — bust',item.role));continue}
      const view=section.bust?{...item,bustView:true}:item;const el=card(view);
      if(section.bust){
        const name=item.displayName||item.name;
        el.querySelector('.character-title').textContent=name;
        el.querySelector('.cover').setAttribute('aria-label','Open bust of '+name);
        el.querySelector('.character-title').setAttribute('aria-label','Open bust files for '+name);
        el.querySelector('.card-downloads').remove();el.querySelector('.tags').remove();
        el.querySelector('.cover-label').textContent='Bust gallery and files';
        if(item.bustCover)el.querySelector('.cover img').src=item.bustCover;else if(bustCovers[id])el.querySelector('.cover img').src='assets/brand/bust-'+bustCovers[id]+'.jpg';
      }
      grid.append(el);
    }
    for(const entry of section.missing||[])grid.append(missingCard(entry.name,entry.role));
    block.append(grid);root.append(block);
  });
  const locked=document.createElement('section');locked.className='campaign-section locked-section';
  locked.append(sectionHeader('An Unreleased Story',''),missingCard('Aveline Glass','The Fairest',true));root.append(locked);
}
function displayFileName(name){return name.replace('Превью из STL','STL preview')}
function renderFiles(item){const target=$('#character-file-list');target.replaceChildren();const files=(item.files||[]).filter(f=>!item.bustView||((f.type==='stl'||f.type==='chitubox')?/bust/i.test(f.relative):f.type==='render'?f.relative.startsWith('Рендеры/Бюст/'):true));$('#file-count').textContent=files.length;const types=[['chitubox','Chitubox'],['stl','STL'],['render','Renders and videos']];for(const [type,label] of types){const matches=files.filter(x=>x.type===type);if(!matches.length)continue;const group=document.createElement('details');group.className='file-group';group.open=type==='chitubox'||(item.bustView&&type==='stl');const summary=document.createElement('summary');const caption=document.createElement('span');caption.textContent=label;const count=document.createElement('span');count.textContent=matches.length;summary.append(caption,count);group.append(summary);let previous='';for(const f of matches){if(f.group!==previous&&type!=='chitubox'){const heading=document.createElement('p');heading.className='file-subgroup';heading.textContent=f.group.split('/').slice(1).map(part=>({'Фигура':'Figure','Бюст':'Bust','Без поддержек':'Unsupported','С поддержками':'Pre-supported','Изображения':'Images','Видео':'Videos','Рендеры':'Renders'}[part]||part)).join(' · ')||label;group.append(heading);previous=f.group}const row=document.createElement('a');row.className='file-row';row.dataset.fileKey=f.key;const name=document.createElement('span');name.className='file-name';name.textContent=displayFileName(f.name);const meta=document.createElement('span');meta.className='file-meta';meta.textContent=f.downloadKind==='archive'?(f.path?'ZIP · '+size(f.archiveBytes):'Archive unavailable'):size(f.bytes);row.append(name,meta);ready(row,f);if(f.path){row.setAttribute('aria-label',f.downloadKind==='archive'?'Download archive '+f.archiveName+' containing '+displayFileName(f.name):'Download '+displayFileName(f.name));if(f.downloadKind==='archive')row.title='Archive '+f.archiveName+' contains '+displayFileName(f.name);}group.append(row)}target.append(group)}}
function showSlide(){displayed=active.gallery.filter(x=>(active.bustView?x.scope==='bust':x.scope!=='bust')&&(variant==='NSFW'?x.label==='NSFW':x.label!=='NSFW'));slide=Math.max(0,Math.min(slide,displayed.length-1));const current=displayed[slide];if(current){$('#gallery-image').src=current.src;$('#gallery-image').alt=(active.displayName||active.name)+' — '+current.label+' '+(slide+1)}else{$('#gallery-image').removeAttribute('src');$('#gallery-image').alt='No renders available'}$('#gallery-counter').textContent=(displayed.length?slide+1:0)+' / '+displayed.length;$('#prev').disabled=slide===0;$('#next').disabled=slide>=displayed.length-1;$('#gallery-note').classList.toggle('missing',active.bustView&&!active.bust);$('#gallery-note').textContent=active.bustView?(!active.bust?'NO BUST STL. Only renders are currently available.':'Bust files are listed separately. The full STL set also includes the character’s parts.'):active.previewNote;for(const b of document.querySelectorAll('[data-variant]'))b.setAttribute('aria-pressed',String(b.dataset.variant===variant));const thumbs=displayed.map((x,i)=>{const b=document.createElement('button');b.className='thumbnail'+(i===slide?' current':'');b.setAttribute('aria-label','Render '+(i+1));b.setAttribute('aria-pressed',String(i===slide));const image=document.createElement('img');image.src=x.src;image.alt='';image.loading='lazy';b.append(image);b.addEventListener('click',()=>{slide=i;showSlide()});return b});$('#gallery-thumbnails').replaceChildren(...thumbs)}
function openGallery(item){$('#gallery').dataset.character=item.id;$('#gallery').dataset.view=item.bustView?'bust':'figure';active=item;slide=0;variant='SFW';$('#gallery-title').textContent=(item.displayName||item.name)+(item.bustView?' — bust':'');$('#character-role').textContent=[item.chapter?'Chapter '+item.chapter:'',item.role].filter(Boolean).join(' · ');$('#character-lore').textContent=item.lore||'A miniature from the Wonderland Leaks Through collection.';$('#gallery-variants').hidden=item.bustView||!item.gallery.some(x=>x.label==='NSFW');$('#character-downloads').replaceChildren(makeButton(item.bustView?'STL — full set':item.model?.scope==='figure'?'STL — figure':'STL — full set',item.bustView?(!item.bust?null:(item.bustModel===undefined?item.model:item.bustModel)):item.model,'primary'),makeButton(item.bustView?'Bust renders — full set':'Renders — full set',item.bustView?item.bustRenders:item.renders,'secondary'),...(item.chitubox&&!item.bustView?[makeButton('Download Chitubox',item.chitubox,'secondary')]:[]));$('#shared-project-note').hidden=data.mode!=='online'&&!item.files?.some(f=>f.shared);$('#shared-project-note').textContent=data.mode==='online'?(data.tier&&data.tier!=='complete'?'Download buttons and file entries link to ZIP archives containing the files in your set.':'Download buttons and file entries link to ZIP archives containing the requested files. “Collection ZIP” contains the entire available collection.'):'The Chibi share one Chitubox project.';renderFiles(item);showSlide();$('#gallery').showModal();$('#gallery').scrollTop=0}
$('#close-gallery').addEventListener('click',()=>$('#gallery').close());$('#prev').addEventListener('click',()=>{slide--;showSlide()});$('#next').addEventListener('click',()=>{slide++;showSlide()});for(const b of document.querySelectorAll('[data-variant]'))b.addEventListener('click',()=>{variant=b.dataset.variant;slide=0;showSlide()});$('#gallery').addEventListener('click',e=>{if(e.target===$('#gallery')){const rect=e.target.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)e.target.close()}});$('#gallery').addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&slide<displayed.length-1){slide++;showSlide()}if(e.key==='ArrowLeft'&&slide>0){slide--;showSlide()}});const allReady=ready($('#download-all'),data.all);if(!allReady)$('#download-all span').textContent='Archive in preparation';else if(data.all.caption)$('#download-all span').textContent=data.all.caption;$('#all-size').textContent=data.all?'ZIP · '+size(data.all.bytes)+(data.all.partial?' · latest files not included':''):'ZIP';$('#publish-note').hidden=data.mode==='local'||(Boolean(data.all&&data.all.path)&&!data.downloadNote);if(data.downloadNote)$('#publish-note').textContent=data.downloadNote;render();

};
